apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  db: postgres
  user: postgres
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: django-credentials
type: Opaque
data:
  secret: eGRQZF9sZHBRZGstYnVCdHhTX3pkOHhPYTAxeg==