apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: bibxml/base
          imagePullPolicy: Never
          args:
            - celery
            - -A
            - indexer
            - worker
            - -l
            - info
            - -c
            - "1"
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis-service:6379
            - name: CELERY_RESULT_BACKEND
              value: redis://redis-service:6379
            - name: DATASET_TMP_ROOT
              value: /code/datasets
            - name: DB_HOST
              value: db-service
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DB_PORT
              value: "5432"
            - name: DB_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DEBUG
              value: "0"
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  name: django-credentials
                  key: secret
            - name: PRIMARY_HOSTNAME
              value: localhost
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 5672
          resources: {}
          volumeMounts:
            - mountPath: /code/datasets
              name: celery-claim0
      restartPolicy: Always
      volumes:
        - name: celery-claim0
          persistentVolumeClaim:
            claimName: celery-claim0
status: {}
