apiVersion: v1
kind: Service
metadata:
  labels:
    app: celery
  name: celery-service
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    app: celery
status:
  loadBalancer: {}
