version: "3.9"

services:
  redis:
    image: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    hostname: db

  web:
    build: .
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    hostname: web-indexer
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  flower:
    image: mher/flower
    hostname: flower
    env_file:
      - ./.env.dev
    depends_on:
      - celery
    ports:
      - "5555:5555"

  celery:
    restart: always
    build:
      context: .
    command: celery -A indexer worker -l info -c 1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
      - ./.celery.env.dev
    depends_on:
      - db
      - redis
      - web

networks:
  default:
    external: true
    name: bibxml_network
