version: "3.9"

services:
  redis:
    image: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    hostname: db
    environment:
      POSTGRES_DB: ${DB_NAME:?missing DB name}
      POSTGRES_USER: ${DB_NAME:?err}
      POSTGRES_PASSWORD: "${DB_SECRET:?missing DB secret (long random string)}"
    networks:
      - default
      - bibxml_indexer_db_net

  web:
    build: .
    restart: "on-failure:10"
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py check --deploy &&
        if [ "$DEBUG" = "1" ]; then
          python manage.py runserver 0.0.0.0:8000
        else
          daphne indexer.asgi:application -p 8000 -b 0.0.0.0
        fi
    volumes:
      - .:/code
    hostname: web-indexer
    ports:
      - "${PORT:?missing port to expose API and GUI under}:8000"
    environment:
      API_SECRET: "${API_SECRET:?missing API secret}"
      DATASET_TMP_ROOT: "/code/datasets"
      PRIMARY_HOSTNAME: ${HOST:?missing main hostname (e.g., localhost for development)}
      DEBUG: ${DEBUG:-0}
      DJANGO_SECRET: "${DJANGO_SECRET:?missing Django secret (long random string)}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_NAME:?err}
      DB_NAME: ${DB_NAME:?err}
      DB_SECRET: "${DB_SECRET:?err}"
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - redis

  celery:
    build: .
    restart: always
    command: celery -A indexer worker -l info -c 1
    volumes:
      - .:/code
      - ./data/datasets:/code/datasets
    environment:
      PRIMARY_HOSTNAME: ${HOST:?err}
      DATASET_TMP_ROOT: "/code/datasets"
      DEBUG: ${DEBUG:-0}
      DJANGO_SECRET: "${DJANGO_SECRET:?err}"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_NAME:?err}
      DB_NAME: ${DB_NAME:?err}
      DB_SECRET: ${DB_SECRET:?err}
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: 1
    depends_on:
      - web
      - db
      - redis

  flower:
    image: mher/flower
    hostname: flower
    environment:
      CELERY_BROKER_URL: "redis://redis:6379"
      CELERY_RESULT_BACKEND: "redis://redis:6379"
    depends_on:
      - celery
    ports:
      - "5555:5555"

networks:
  bibxml_indexer_db_net:
    name: bibxml_indexer_db_net
