openapi: 3.0.1

info:
  title: BibXML datasets indexer
  description: This is BibXML indexer API
  contact:
    email: open.source@ribose.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.2

servers:
- url: http://localhost:8001/api/v1

paths:
  /indexer/{dataset}/run:
    get:
      summary: Run Indexer task for a dataset
      description: Creates Celery task that runs indexer for chosen datasets if it
        possible
      operationId: runIndexer
      parameters:
      - name: dataset
        in: path
        description: Name of dataset to index
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        404:
          description: Unknown dataset to index
          content: {}

        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /indexer/{dataset}/stop:
    get:
      summary: Stop Indexer task for a dataset if it possible
      description: Stops celery indexer task for chosen dataset if it running
      operationId: stopIndexer
      parameters:
      - name: dataset
        in: path
        description: Name of indexing dataset
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'

      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'

        404:
          description: Unknown dataset to index
          content: {}

        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /indexer/{dataset}/reset:
    get:
      summary: Reset Indexer task for a dataset and delete all records at DB
      description: Stops celery indexer task for chosen dataset if it running 
        and delete all indexed records at database
      operationId: resetIndexer
      parameters:
      - name: dataset
        in: path
        description: Name of indexing dataset
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'

        404:
          description: Unknown dataset to index
          content: {}

        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'



  /indexer/{dataset}/status:
    get:
      summary: Shows Indexer task status for selected dataset
      description: Shows celery indexer task status
      operationId: indexerStatus
      parameters:
      - name: dataset
        in: path
        description: Name of indexing dataset
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      responses:
        200:
          description: successful operation, shows index current status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexerStatus'
        404:
          description: Unknown dataset to index
          content: {}

components:

  schemas:

    IndexableDatasets:
      type: string
      enum:
      - ecma
      - nist
      - ietf
      - itu-r
      - calconnect
      - cie
      - iso
      - bipm
      - iho

    SuccessMessage:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              description: Human readable success message

    ErrorMessage:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              description: Code for automatic error processing
            message:
              type: string
              description: Human readable error message


    IndexerStatus:
      type: object
      properties:
        task_id:
          type: string
          format: uuid
          description: Celery task ID
        indexed_files:
          type: integer
          description: Counter of processed YAML files
        started_at:
          type: string
          format: datetime
          description: Task start timestamp
        stopped_at:
          type: string
          format: datetime
          description: Task stop timestamp
        message:
          type: string
          description: Human readable results of this run
        commit:
          type: string
          description: Hex of HEAD commit of indexing dataset
        status:
          type: string
          description: Indexer Status
          enum:
          - running
          - completed
          - failed
