openapi: 3.0.1

info:
  title: BibXML indexer
  description: |
    BibXML indexer API.
    NOTE: Not all 500 responses are currently provided in the shape of JSON.
  contact:
    email: open.source@ribose.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: v1

servers:
- url: /api/v1

paths:
  /indexer/{dataset}/run:
    get:
      summary: Queues dataset indexing
      description: Creates Celery task that runs indexer for chosen datasets if it
        possible
      operationId: runIndexer
      parameters:
      - name: dataset
        in: path
        description: Dataset ID
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      - name: refs
        in: query
        description: Comma-separated list of refs to index (if not provided, the entire dataset is reindexed)
        schema:
          type: array
          items:
            type: string
        style: form
        explode: false
      responses:
        200:
          description: Indexing task had been queued (does not mean indexing completed without errors)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        500:
          description: Queueing failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /indexer/{dataset}/reset:
    get:
      summary: Clear dataset index
      description: Clears indexed data for given dataset; notably, does not abort any indexing tasks queued or progressing
      operationId: resetIndex
      parameters:
      - name: dataset
        in: path
        description: Dataset ID
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /indexer/{dataset}/status:
    get:
      summary: Shows latest indexing task status
      description: Returns a list of indexing tasks for given dataset, starting from most recently started task
      operationId: indexerStatus
      parameters:
      - name: dataset
        in: path
        description: Dataset ID
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'
      responses:
        200:
          description: successful operation, shows index current status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexerStatus'

  /tasks/{task_id}/stop:
    get:
      summary: Attempts to stop specified task 
      description: Revokes given task, and attempts to terminate if running. Is not guaranteed to take effect immediately
      operationId: stopTask
      parameters:
      - name: task_id
        in: path
        description: Task ID, can be obtained by checking dataset index status
        required: true
        schema:
          $ref: '#/components/schemas/IndexableDatasets'

      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /tasks/stop-all:
    get:
      summary: Cancel any pending tasks
      description: Revokes any pending tasks. Notably, is not guaranteed to terminate the already running ones
      operationId: stopAllTasks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        500:
          description: operation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:

    IndexableDatasets:
      type: string
      enum:
      - ecma
      - nist
      - ietf
      - itu-r
      - calconnect
      - cie
      - iso
      - bipm
      - iho

    SuccessMessage:
      type: object
      properties:
        message:
          type: string
          description: Human-readable success message

    ErrorMessage:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              description: Code for automatic error processing
            message:
              type: string
              description: Human-readable error message

    IndexerStatus:
      type: object
      properties:
        tasks:
          description: A list of most recent indexing tasks for given dataset
          type: array
          items:
            type: object
            description: Describes a task. Currently, only task ID is reliably provided
            required:
              - task_id
            properties:
              task_id:
                format: string
                description: Task ID; can be used to cancel this task using the tasks endpoint
              started_at:
                type: string
                format: datetime
              completed_at:
                type: string
                format: datetime
              status:
                type: string
                description: Short status keyword
              outcome_summary:
                type: string
                description: Human-readable description of successful or unsuccesful outcome, if achieved
              error:
                type: object
                description: Error information for failed task, if available
                properties:
                  type:
                    type: string
                  message:
                    type: string
              requested_refs:
                type: array
                description: Refs that were requested for indexing.
                items:
                  type: string
              progress:
                type: object
                required:
                  - indexed
                properties:
                  total:
                    description: Total number of source files found
                    type: integer
                  indexed:
                    description: Total number of indexed files
                    type: integer
