apiVersion: v1
kind: Service
metadata:
  labels:
    app: flower
  name: flower-service
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    app: flower
status:
  loadBalancer: {}
